"""add_last_modified_by_column

Revision ID: 0ab9a1de5499
Revises: 1a5328c30b78
Create Date: 2026-01-13 19:20:35.620981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab9a1de5499'
down_revision = '1a5328c30b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('attendance', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('attendance_summary', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('class_students', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('enrollments', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('modalities', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('student_health_data', schema='students') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('student_health_data', schema='students') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('modalities', schema='academy') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('enrollments', schema='academy') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('class_students', schema='academy') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('attendance_summary', schema='academy') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('attendance', schema='academy') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('activities', schema='academy') as batch_op:
        batch_op.drop_column('last_modified_by')

    # ### end Alembic commands ###
