"""ajuste na classeSchedule para is_active

Revision ID: 0d3a5b09a662
Revises: bd67bad4f6ea
Create Date: 2026-01-02 18:25:27.006943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3a5b09a662'
down_revision = 'bd67bad4f6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
