"""ajuste na tabela de Invoice

Revision ID: 1a5328c30b78
Revises: 8344b177958d
Create Date: 2026-01-06 16:20:42.739430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5328c30b78'
down_revision = '8344b177958d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('description_paid', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.drop_column('description_paid')
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
