"""criando tabela de atividades academy

Revision ID: 2c15f7d3ff04
Revises: 074b1844180f
Create Date: 2025-12-29 12:26:50.459892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c15f7d3ff04'
down_revision = '074b1844180f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='academy'
    )
    with op.batch_alter_table('attendance', schema='academy') as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], referent_schema='students')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema='academy') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_student_id_fkey'), 'students', ['student_id'], ['id'], referent_schema='students', ondelete='CASCADE')

    op.drop_table('activities', schema='academy')
    # ### end Alembic commands ###
