"""nova coluna de Plan para lidar com tipo de mensalidade

Revision ID: 3c2cb25af5bd
Revises: 06b6f481de50
Create Date: 2026-01-06 10:53:25.610472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2cb25af5bd'
down_revision = '06b6f481de50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema='finance') as batch_op:
        batch_op.drop_column('duration_months')

    # ### end Alembic commands ###
