"""criado colunas para gerar pix

Revision ID: 489af0663635
Revises: 988213247a36
Create Date: 2026-01-04 12:42:09.077501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489af0663635'
down_revision = '988213247a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['external_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###
