"""ajustando coluna activity_id

Revision ID: 5b86d061caf4
Revises: 2c15f7d3ff04
Create Date: 2025-12-29 12:54:36.788389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b86d061caf4'
down_revision = '2c15f7d3ff04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'activities', ['activity_id'], ['id'], referent_schema='academy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
