"""criando estrutura students

Revision ID: 6a118168b5ad
Revises: 1fa2b58514f7
Create Date: 2025-12-29 10:55:51.377480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a118168b5ad'
down_revision = '1fa2b58514f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='students'
    )
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.create_index(batch_op.f('ix_students_students_cpf'), ['cpf'], unique=True)

    op.create_table('student_health_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.String(length=3), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='students'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_health_data', schema='students')
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_students_cpf'))

    op.drop_table('students', schema='students')
    # ### end Alembic commands ###
