"""add is_active and detail columns to student

Revision ID: 8193aa27dd9f
Revises: beae845682a4
Create Date: 2025-12-29 14:17:33.266993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8193aa27dd9f'
down_revision = 'beae845682a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('medical_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('address_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address_number')
        batch_op.drop_column('address')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('emergency_phone')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('medical_notes')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
