"""add status to activities

Revision ID: 82c20eff8928
Revises: d8c4f61ec3e9
Create Date: 2026-01-02 10:13:03.431851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c20eff8928'
down_revision = 'd8c4f61ec3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema='academy') as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
