"""criado tabela de expense

Revision ID: 8d62cf39f334
Revises: 489af0663635
Create Date: 2026-01-04 19:19:01.002621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d62cf39f334'
down_revision = '489af0663635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.drop_constraint(batch_op.f('invoices_external_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.create_unique_constraint(batch_op.f('invoices_external_id_key'), ['external_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('expenses', schema='finance')
    # ### end Alembic commands ###
