"""novo modelo para finaceiro

Revision ID: 917d012076d8
Revises: 0d3a5b09a662
Create Date: 2026-01-02 19:27:18.522269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '917d012076d8'
down_revision = '0d3a5b09a662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pix_copy_paste', sa.Text(), nullable=True))
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_foreign_key(None, 'plans', ['plan_id'], ['id'], referent_schema='finance')
        batch_op.drop_column('update_at')
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('pix_copy_paste')
        batch_op.drop_column('external_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('amount')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
