"""plan_id en studentt

Revision ID: 988213247a36
Revises: 917d012076d8
Create Date: 2026-01-03 02:37:05.261550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988213247a36'
down_revision = '917d012076d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'plans', ['plan_id'], ['id'], referent_schema='finance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
