"""adicionando campos de status e saude em alunos

Revision ID: beae845682a4
Revises: e3e4148556ee
Create Date: 2025-12-29 14:11:52.140011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beae845682a4'
down_revision = 'e3e4148556ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
