"""ajuste em Health Student

Revision ID: c82c3b83b1ec
Revises: 8193aa27dd9f
Create Date: 2025-12-29 16:24:36.549932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82c3b83b1ec'
down_revision = '8193aa27dd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_health_data', schema='students') as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_health_data', schema='students') as batch_op:
        batch_op.drop_column('height')

    # ### end Alembic commands ###
