"""ajuste ne permisao de email,phone

Revision ID: d32381fd6b62
Revises: eaf0245d15fc
Create Date: 2026-02-04 10:04:40.107210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32381fd6b62'
down_revision = 'eaf0245d15fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema='core') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('settings', schema='core') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('welcome_email_logs', schema='core') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.drop_constraint(batch_op.f('students_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema='students') as batch_op:
        batch_op.create_unique_constraint(batch_op.f('students_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('welcome_email_logs', schema='core') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('settings', schema='core') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('audit_logs', schema='core') as batch_op:
        batch_op.drop_column('last_modified_by')

    # ### end Alembic commands ###
