"""add status to class_schedule

Revision ID: d8c4f61ec3e9
Revises: c82c3b83b1ec
Create Date: 2025-12-30 21:18:59.670584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c4f61ec3e9'
down_revision = 'c82c3b83b1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
