"""tabela enviroll

Revision ID: e3e4148556ee
Revises: 5b86d061caf4
Create Date: 2025-12-29 13:23:26.027798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e4148556ee'
down_revision = '5b86d061caf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['academy.class_schedule.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academy'
    )
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedule', schema='academy') as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.drop_table('enrollments', schema='academy')
    # ### end Alembic commands ###
