"""add_audit_to_finance_schema

Revision ID: eaf0245d15fc
Revises: 0ab9a1de5499
Create Date: 2026-01-13 19:32:16.755218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf0245d15fc'
down_revision = '0ab9a1de5499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('plans', schema='finance') as batch_op:
        batch_op.add_column(sa.Column('last_modified_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema='finance') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('invoices', schema='finance') as batch_op:
        batch_op.drop_column('last_modified_by')

    with op.batch_alter_table('expenses', schema='finance') as batch_op:
        batch_op.drop_column('last_modified_by')

    # ### end Alembic commands ###
